server:
  port: 7003
spring:
  application:
    name: my-wf-gatway-server
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true #显示浏览器中的状态栏显示ip
zuul:
  routes:
    myuserconsumer:
      path: /house/**        #http://localhost:7003/userserver/user/show?uid=2
      serviceId: user-consumer-fegin
