server:
  port: 8001


spring:
  application:
    name: order-provider
  ldap:
    base-environment:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bug?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ok


eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zb.entity
